# Generated by Django 5.1.6 on 2025-04-16 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_node_name_workflowexecution_execution_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='execution_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
