# Generated by Django 5.1.6 on 2025-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflowexecution_execution_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='node',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
