# Generated by Django 5.1.6 on 2025-04-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_node_options_node_retry_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_input', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='workflows.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='workflows.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_connections', to='workflows.node')),
                ('source_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_port', to='workflows.nodeport')),
                ('target_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_port', to='workflows.nodeport')),
            ],
        ),
    ]
