# Generated by Django 5.1.6 on 2025-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_nodeport_nodeconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeport',
            name='node',
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='execution_context',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='variables',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='NodeConnection',
        ),
        migrations.DeleteModel(
            name='NodePort',
        ),
    ]
